fix(getPublicKey): hashing and arrayify message
energywebfoundation/iam-client-lib pull request #101
Opened 2021-02-01 19:16 UTC by jrhender

arrayification is necessary in order for WalletConnect signatures to work. eth_sign expects message in bytes:
https://docs.walletconnect.org/json-rpc-api-methods/ethereum#eth_sign
keccak256 hash is applied in order to obtain message with length of 32 bytes. This allows Metamask to display a coherent hex value when signing.

2021-02-02 09:52 UTC, JGiter approved these changes

2021-02-02 11:37 UTC, dwojno commented
@jrhender please not merge this PR, cause I've added your changes to [this PR](https://github.com/energywebfoundation/iam-client-lib/pull/95) and will be hard to merge conflicts right now :)

2021-02-02 11:37 UTC, dwojno requested changes
@jrhender please not merge this PR, cause I've added your changes to [this PR](https://github.com/energywebfoundation/iam-client-lib/pull/95) and will be hard to merge conflicts right now :)

2021-02-03 07:53 UTC, dwojno approved these changes

2021-02-08 21:08 UTC, merged