GH action for iam-client-lib
energywebfoundation/iam-client-lib pull request #207
Opened 2021-07-08 12:21 UTC by royki

- Migrate Travis CI to GitHub Action

2021-07-14 18:28 UTC, jrhender reviewed
Just one comment. Also need to remove the .travis.yml file please.

As a stretch goal, would be interested if this issue can be fixed while we are working on this 😄  Any thoughts on this @royki ? If it's too much work and out of scope for this, that's okay too https://github.com/energywebfoundation/iam-client-lib/issues/191

Also, would be good to get @JGiter 's review on this PR as well as he is responsible for iam-client-lib now and has some experience with CI.

2021-07-14 18:28 UTC, jrhender commented on .github/workflows/deploy.yml
> +    branches: [ 'develop' ]
Why not also `master` here?
```suggestion
    branches: [ 'develop' , 'master' ]
```

2021-07-15 09:34 UTC, JGiter requested changes

2021-07-15 09:34 UTC, JGiter commented on .github/workflows/deploy.yml
> +          npm run build --prod
I guess this is not needed

2021-07-15 09:34 UTC, JGiter commented on .github/workflows/deploy.yml
> +          npm run build --prod
```suggestion
```

2021-07-15 21:37 UTC, jrhender approved these changes
Looks good to me 👍

2021-07-16 07:51 UTC, JGiter approved these changes

2021-07-19 08:10 UTC, merged