feat(WalletConnect): change to public WalletConnect relay
energywebfoundation/iam-client-lib pull request #292
Opened 2021-10-08 07:57 UTC by Harasz

2021-10-08 09:28 UTC, JGiter reviewed
Have you managed to connect with this bridge?

2021-10-08 09:49 UTC, Harasz commented
I have with Volta RPC, but there is a problem with signing message bc method `eth_sign` is not supported.
On our dev RPC I haven't, dev RPC is not supporting `skipCache` param in request.

2021-10-08 10:35 UTC, JGiter commented
I can't get to signing, because after QR code scanning there are endless requests to Volta

2021-10-11 09:18 UTC, JGiter commented on src/iam/iam-base.ts
> +            this._walletConnectSignMessage = walletConnector.signMessage.bind(walletConnector);
There a lot of places in code where we need signing. Wouldn't be better to implement Signer on top of wallet connect?

2021-10-15 15:34 UTC, jrhender requested changes
The fix looks good, nice work. It's annoying we needed to use `patch-package` but at least the change isn't very big.

Could you somehow point to the GitHub issue that you created in the code? Maybe squash your commit and add the link to the commit messages? My goal is just to have a way for future devs to know why this was put in and when they can try to remove it.

2021-10-18 09:55 UTC, merged