feat: update staking pool tests
energywebfoundation/iam-client-lib pull request #371
Opened 2021-12-08 09:47 UTC by hejkerooo

- fixed staking-pool tests with claim manager integration,
- disabled tests for not used staking,

2021-12-08 10:14 UTC, Harasz commented on src/init.ts
> -        return { cacheClient, domainsService, stakingService, assetsService, connectToDidRegistry, stakingPoolService };
Is this intentional?

2021-12-08 10:29 UTC, JGiter requested changes

2021-12-08 10:29 UTC, JGiter commented on e2e/staking-pool.e2e.ts
> +        expect(true).toBe(true);
Left from debug?

2021-12-08 13:38 UTC, hejkerooo commented on e2e/staking-pool.e2e.ts
> +        expect(true).toBe(true);
yeah, will remove later, thx

2022-01-04 15:18 UTC, Harasz commented
@hejkerooo What is the status of this PR?

2022-01-10 09:28 UTC, closed without merging