feature/document and test selfsigned claims
energywebfoundation/iam-client-lib pull request #425
Opened 2022-01-12 12:04 UTC by JGiter

2022-01-12 16:47 UTC, jrhender commented
@JGiter I will take a look eventually but if @Harasz, @nichonien , @Passerino , @dawidgil (in no particular order) have time to review and approve, that would work too 👍

2022-01-13 05:52 UTC, nichonien approved these changes

2022-01-13 10:14 UTC, Harasz requested changes
We should be consistent in the method of checking asynchronous functions. It is possible that there are more of these situations in the code.

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +                expect(issuedToken).not.toBeUndefined();
```suggestion
                expect(issuedToken).toBeDefined();
```
Maybe to simplify.

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            expect(claimManager.hasRole(addressOf(subjectDID), namehash(role), version)).resolves.toBe(true);
```suggestion
            expect(await claimManager.hasRole(addressOf(subjectDID), namehash(role), version)).toBe(true);
```

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            return expect(claimsService.hasOnChainRole(assetDID, `${roleName1}.${root}`, version)).resolves.toBe(true);
```suggestion
            return expect(await claimsService.hasOnChainRole(assetDID, `${roleName1}.${root}`, version)).toBe(true);
```

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            return expect(claimsService.hasOnChainRole(rootOwnerDID, `${roleName2}.${root}`, version)).resolves.toBe(
```suggestion
            return expect(await claimsService.hasOnChainRole(rootOwnerDID, `${roleName2}.${root}`, version)).toBe(
```

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            return expect(claimsService.hasOnChainRole(rootOwnerDID, `${roleName3}.${root}`, version)).resolves.toBe(
```suggestion
            return expect(await claimsService.hasOnChainRole(rootOwnerDID, `${roleName3}.${root}`, version)).toBe(
```

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            expect(subjectDoc.service.find((s) => s.serviceEndpoint === claimUrl && s.claimType === claimType));
expect to what? I think toBeDefined

2022-01-13 10:14 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            expect(assetDoc.service.find((s) => s.claimType === claimType && s.serviceEndpoint === claimUrl));
expect what?

2022-01-13 10:14 UTC, Harasz commented on src/modules/didRegistry/didRegistry.service.ts
> +            console.log('updating document of:', did);
Do we need this here?

2022-01-13 12:02 UTC, Harasz requested changes

2022-01-13 12:02 UTC, Harasz commented on jest.config.js
> +    testRegex: "(/(e2e|src)/claims.service.(e2e|spec)\\.ts$)",
Remove this change

2022-01-13 12:02 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            expect(assetDoc.service.find((s) => s.claimType === claimType && s.serviceEndpoint === claimUrl)).toBeDefined;
```suggestion
            expect(assetDoc.service.find((s) => s.claimType === claimType && s.serviceEndpoint === claimUrl)).toBeDefined();
```

2022-01-13 12:02 UTC, Harasz commented on e2e/claims.service.e2e.ts
> +            expect(subjectDoc.service.find((s) => s.serviceEndpoint === claimUrl && s.claimType === claimType)).toBeDefined;
```suggestion
            expect(subjectDoc.service.find((s) => s.serviceEndpoint === claimUrl && s.claimType === claimType)).toBeDefined();
```

2022-01-13 13:58 UTC, Harasz approved these changes

2022-01-17 08:52 UTC, merged