fix: setup nats connection options
energywebfoundation/iam-client-lib pull request #433
Opened 2022-01-14 14:35 UTC by hejkerooo

2022-01-14 14:40 UTC, Harasz requested changes

2022-01-14 14:40 UTC, Harasz commented on src/modules/messaging/messaging.service.ts
> -import { executionEnvironment, ExecutionEnvironment } from '../../utils/detectEnvironment';
And why is that?

2022-01-14 14:48 UTC, JGiter commented on src/modules/messaging/messaging.service.ts
> +            reconnect: true,
it is true by default

2022-01-14 14:59 UTC, hejkerooo commented on src/modules/messaging/messaging.service.ts
> -import { executionEnvironment, ExecutionEnvironment } from '../../utils/detectEnvironment';
fixed

2022-01-14 15:05 UTC, Harasz approved these changes

2022-01-17 07:59 UTC, JGiter approved these changes

2022-01-20 11:15 UTC, merged

2022-02-28 12:16 UTC, ewf-devops commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/4.1.0)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: