Wpurdum/#icl 281
energywebfoundation/iam-client-lib pull request #562
Opened 2022-05-20 14:05 UTC by whitneypurdum

### Description

- Remove QUICKSTART.md
- Add command to copy over README to index.md in husky pre-commit

### Contributor checklist

- [ ] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [ ] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [ ] Tests - add new or updated existed test for changes you made.
- [ ] Migration guide - add migration guide for every breaking change.
- [ ] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

2022-05-20 14:21 UTC, whitneypurdum commented
Do I need to bump the version on this? It auto-bumped it in package-lock from "5.1.0-alpha.28" to "6.0.0-alpha.1", but I didn't check it in .

2022-05-20 14:29 UTC, jrhender commented
> Do I need to bump the version on this? It auto-bumped it in package-lock from "5.1.0-alpha.28" to "6.0.0-alpha.1", but I didn't check it in .

Hmm, no, I don't think you need to bump the version

2022-05-20 14:30 UTC, jrhender requested changes
I think the `fix` commits should be `docs`, as to me, `fix` implies a bug fix of some kind to the actual code

2022-05-24 09:16 UTC, jrhender approved these changes

2022-05-24 09:17 UTC, merged

2022-05-24 09:26 UTC, ewf-devops commented
:tada: This PR is included in version 6.0.0-alpha.3 :tada:

The release is available on:
- [npm package (@canary dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/6.0.0-alpha.3)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v6.0.0-alpha.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-15 09:27 UTC, ewf-devops commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/6.0.0)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: