feat/ICL-309 add status to vc
energywebfoundation/iam-client-lib pull request #569
Opened 2022-05-27 11:27 UTC by JGiter

### Description

### Contributor checklist

- [ ] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [ ] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [ ] Tests - add new or updated existed test for changes you made.
- [ ] Migration guide - add migration guide for every breaking change.
- [ ] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.types.ts
> +  /** Allows to track accuracy or relevance of credential */
```suggestion
  /** Indicates if credential is actual of the time of verification */
```

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +  /** Sets location of the credential status */
Complete the documentation

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +  private _addStatusToCredential(credential: Credential<RoleCredentialSubject>) {
```suggestion
  private addStatusToCredential(credential: Credential<RoleCredentialSubject>) {
```

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +        credentialStatus = (await this._addStatusToCredential(credential)).credentialStatus;
```suggestion
        credentialStatus = (await this.addStatusToCredential(credential)).credentialStatus;
```

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +        credentialStatus = (await this._addStatusToCredential(credential)).credentialStatus;
```suggestion
        const credentialStatus = (await this._cacheClient.addStatusToCredential(credential)).credentialStatus;
```
Do not override incoming parameters especially when it's not a primitive type

2022-05-30 06:54 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +        credentialStatus = (await this._addStatusToCredential(credential)).credentialStatus;
Do we need `addStatusToCredential` method in claim service, we can just use that one from cache client

2022-05-30 08:32 UTC, Harasz commented on e2e/claim-revocation.e2e.ts
> +const {id} = utils;
```suggestion
const { id } = utils;
```

2022-05-30 08:32 UTC, Harasz commented on src/modules/claims/claims.service.ts
> +  private async addSsiCredentialStatus({sub, role, version, issuerFields}: AddSsiCredentialStatusOptions  ) {
```suggestion
  private async addSsiCredentialStatus({sub, role, version, issuerFields}: AddSsiCredentialStatusOptions): Promise<!type!> {
```

2022-05-30 14:04 UTC, Harasz requested changes
It's not gonna work. During credential creation we are generating different UUID and based on UUID SSI-Hub is generating credential status. Fetching credential status should be done in verifiable credential  service during VC creation.

2022-06-02 09:09 UTC, JGiter commented
> It's not gonna work. During credential creation we are generating different UUID and based on UUID SSI-Hub is generating credential status. Fetching credential status should be done in verifiable credential service during VC creation.

@Harasz I fixed that. Please look again

2022-06-02 09:26 UTC, Harasz requested changes
Looks good now, just remove unused code

2022-06-02 09:26 UTC, Harasz commented on src/modules/claims/claims.types.ts
> +}
```suggestion
```

2022-06-02 09:26 UTC, Harasz commented on src/modules/claims/claims.types.ts
> +import { IssuerFields } from '../verifiable-credentials';
```suggestion
```

2022-06-02 10:47 UTC, Harasz approved these changes

2022-06-02 10:49 UTC, merged

2022-06-02 11:00 UTC, ewf-devops commented
:tada: This PR is included in version 6.0.0-alpha.10 :tada:

The release is available on:
- [npm package (@canary dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/6.0.0-alpha.10)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v6.0.0-alpha.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-15 09:27 UTC, ewf-devops commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/6.0.0)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: