Update @ew-did-registry@0.8.1-alpha.1122
energywebfoundation/iam-client-lib pull request #703
Opened 2023-06-19 12:39 UTC by JGiter

### Description

### Contributor checklist

- [x] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [x] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [x] Tests - add new or updated existed test for changes you made.
- [x] Migration guide - add migration guide for every breaking change.
- [x] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

2023-06-20 07:42 UTC, nichonien approved these changes

2023-06-20 08:08 UTC, jrhender requested changes

2023-06-20 08:08 UTC, jrhender commented on package.json
> +    "@ew-did-registry/did-ipfs-store": "^0.8.1-alpha.1122.0",
I'm not sure we want to update `did-ipfs-store` yet, until we are confident that EW's IPFS cluster infrastructure is suitable. Let's discuss this further

2023-06-21 15:20 UTC, jrhender approved these changes
A small question but it looks good to me 👍

2023-06-21 15:20 UTC, jrhender commented on e2e/utils/setUpIpfsCluster/docker-compose.yml
Is `setUpIpfsCluster` needed even if we've kept `"@ew-did-registry/did-ipfs-store"` as `"^0.7.1-alpha.816.0"`?

2023-06-22 05:05 UTC, JGiter commented on e2e/utils/setUpIpfsCluster/docker-compose.yml
No, it is not used now. I kept it since we are moving to cluster anyway

2023-06-22 05:05 UTC, merged

2023-06-22 05:35 UTC, ewf-devops commented
:tada: This PR is included in version 8.0.1-alpha.2 :tada:

The release is available on:
- [npm package (@canary dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/8.0.1-alpha.2)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v8.0.1-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-24 10:10 UTC, ewf-devops commented
:tada: This PR is included in version 8.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iam-client-lib/v/8.0.1)
- [GitHub release](https://github.com/energywebfoundation/iam-client-lib/releases/tag/v8.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: