[MYEN-497] add implementation of searching namespaces
energywebfoundation/iam-client-lib pull request #75
Opened 2020-12-17 12:37 UTC by dwojno

2020-12-17 13:30 UTC, manihagh requested changes

2020-12-17 13:40 UTC, dwojno commented on src/cacheServerClient/cacheServerClient.ts
> +    const { data } = await this.httpClient.get<IOrganization[]>(`/namespace/search/${search}`);
Yes, for now yes, I think I should make this a draft PR, cause I wanted to wait with this until we add changes to cache server.

2021-01-11 12:54 UTC, dwojno commented on src/cacheServerClient/cacheServerClient.ts
> +    const { data } = await this.httpClient.get<IOrganization[]>(`/namespace/search/${search}`);
@manihagh I've added all necessary changes to iam-cache-server, so I've updated this PR, to make it work :)

2021-01-11 14:26 UTC, manihagh approved these changes

2021-01-12 11:42 UTC, merged